### ISSUE TITLE
Need to add support for batch updates

### ISSUE THREAD

**Issue by YourTechBud** [spaceuptech/space-api-js#13]
The HTTP endpoint is ready need to get that in place. Let's decide how will we expose the api to the users.

**Comment by Jayesh333** [comment]
The transaction support added works more like a batch. So let's make that more explicit and rename it to `batch`. 

Here's how the batch API should look for javascript:
```js
const batch = db.beginBatch();
batch.add(db.insert(col).docs(...docs));
batch.add(db.update(col).where(whereClause).set())

// Apply batch
batch.apply().then(res => ...).catch(ex => ...)
```

**Comment by Jayesh333** [comment]
Need to solve #18 first

**Comment by YourTechBud** [comment]
#18 is closed. Can we start work on this?
