### ISSUE TITLE
db.liveQuery(...).where(condition).subscribe(onSnapshot, onError) - onSnapshot not called for deletes

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [spaceuptech/space-api-js#23]
Expected: onSnapshot to be called when db.delete(...) is called

Actual: Document(s) are deleted but onSnapshot is not called

delete

    removeTodo(id) {
        db.delete('todos').where(and(cond('id', '==', id))).one().then(res => {
            if (res.status !== 200) {
                console.log('Delete Failed:', res)
            }

        }).catch(ex => {
            // Exception occured while processing request
            console.log('Delete Exception:', ex)
        });
    }

subscription

    componentDidMount() {
        // Get user id from local storage
        const userId = localStorage.getItem('userId')

        const onSnapshot = (docs, type) => {
            console.log('onSnapshot > docs', docs)
            this.setState({todos: docs}, () => {
                console.log('onSnapshot > setState > this.state.todos', this.state.todos)
            })
        }
        const onError = (err) => {
            console.log('Live query error', err)
        }
        const condition = cond('userId', '==', userId);
        db.liveQuery("todos")
            .where(condition)
            .subscribe(onSnapshot, onError)
        db.liveQuery("todos")
            .where({}) // testing not sure if this even works
            .subscribe((doc) => {
                console.log('subscribe > doc', doc)
            }, onError)
    }

**Comment by YourTechBud** [comment]
@Jayesh333 close spaceuptech/space-cloud#177 on completion.

**Comment by YourTechBud** [comment]
@MichaelLeeHobbs is this bug resolved now? I guess #24 was the reason this happened right?

**Comment by YourTechBud** [comment]
Resolved
