### ISSUE TITLE
Conditions for the same field gets overwritten

### ISSUE THREAD

**Issue by Jayesh333** [spaceuptech/space-api-js#30]
```js
where(and(cond('a', '>=', 'somevalue'), cond('b', '<=', 'someothervalue')))
```
For the above example only the second condition is reflected because the first gets overwritten by the second condition

**Comment by YourTechBud** [comment]
@Jayesh333 have you resolved this issue?

**Comment by Jayesh333** [comment]
No @YourTechBud
